### ISSUE TITLE
node_modules не место в репе

### ISSUE THREAD

**Issue by MaccKOT** [matveisch/todo-list#1]
Создай в корне проекта файл .gitignore и добавь туда
node_modules
.DS_store
.idea (потому что файлы от редактора кода тоже никому не нужны)

https://www.atlassian.com/ru/git/tutorials/saving-changes/gitignore

**Comment by matveisch** [comment]
Да, знаю, что так надо делать, но часто просто не запариваюсь с этим. Но спасибо за правку и совет (только что увидел)!
